esphome:
  name: esp32-rfid-access-controller
  friendly_name: RFID Access Controller

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

output:
  - platform: gpio
    pin: GPIO25
    id: green_led

  - platform: gpio
    pin: GPIO26
    id: red_led

  - platform: ledc
    pin: GPIO14
    id: buzzer

  - platform: ledc
    pin: GPIO13
    id: servo_pwm
    frequency: 50 Hz

script:
  - id: green_flash
    then:
      - output.turn_on: green_led
      - delay: 2s
      - output.turn_off: green_led

  - id: red_flash
    then:
      - output.turn_on: red_led
      - delay: 2s
      - output.turn_off: red_led
    
  - id: granted_beep
    then:
      - output.turn_on: buzzer
      - output.ledc.set_frequency:
          id: buzzer
          frequency: 2000Hz
      - output.set_level:
          id: buzzer
          level: 50%
      - delay: 150 ms
      - output.turn_off: buzzer

  - id: denied_beep
    then:
      - output.turn_on: buzzer
      - output.ledc.set_frequency:
          id: buzzer
          frequency: 700Hz
      - output.set_level:
          id: buzzer
          level: 50%
      - delay: 150 ms
      - output.turn_off: buzzer
      - delay: 120 ms
      - output.turn_on: buzzer
      - delay: 150 ms
      - output.turn_off: buzzer
      
  - id: unlock_door
    then:
      - servo.write:
          id: door_servo
          level: 40%
      - delay: 3s
      - servo.write:
          id: door_servo
          level: -40%

servo:
  - id: door_servo
    output: servo_pwm
    auto_detach_time: 1s

text_sensor:
  - platform: template
    name: "Last RFID Tag"
    id: last_rfid_tag

  - platform: template
    name: "Access Result"
    id: access_result

rc522_spi:
  cs_pin: GPIO27
  reset_pin: GPIO22
  update_interval: 1s

  on_tag:
    then:
      - lambda: |-
          ESP_LOGI("rfid", "Tag scanned: %s", x.c_str());

          id(last_rfid_tag).publish_state(x);

          if (x == "66-7D-C3-06") {
            ESP_LOGI("access", "ACCESS GRANTED");

            id(access_result).publish_state("Granted");

            id(red_led).turn_off();
            id(green_flash).execute();
            id(granted_beep).execute();
            id(unlock_door).execute();

          } else {
            ESP_LOGW("access", "ACCESS DENIED");

            id(access_result).publish_state("Denied");
            
            id(red_flash).execute();
            id(green_led).turn_off();
            id(denied_beep).execute();
          }

button:
  - platform: template
    name: Test_Green_Led
    id: button_template_1
    on_press:
      - then:
          - script.execute: green_flash
  - platform: template
    name: Test_Red_Led
    id: button_template_2
    on_press:
      - then:
          - script.execute: red_flash
  - platform: template
    name: Open Door
    id: button_template_3
    on_press:
      - then:
          - script.execute: unlock_door
  - platform: template
    name: Granted Sound
    id: button_template_4
    on_press:
      - then:
          - script.execute: granted_beep
  - platform: template
    name: Denied Sound
    id: button_template_5
    on_press:
      - then:
          - button.press: button_template_5
sensor:
  - platform: wifi_signal
    name: Wifi signal
    id: sensor_wifi_signal_1
    update_interval: 60s

switch:
  - platform: output
    name: Greed_Led_On-off
    output: green_led
    id: switch_output_1

  - platform: output
    name: Red_Led_On-off
    output: red_led
    id: switch_output_2
